sudo: required
language: python
python:
- '3.5'
before_install:
- echo "It is-a-me, Mario!"
- echo "Trigger a fucking build already man."
install:
- pip install -r requirements.txt
services:
- redis-server
script: python run_tests.py
notifications:
  email: false
after_success:
- echo "Bah bye."
