sudo: required
language: python
python:
- '3.5'
before_install:
- openssl aes-256-cbc -K $encrypted_58fea6fcf709_key -iv $encrypted_58fea6fcf709_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- mv ./deploy_rsa /tmp/deploy_rsa
- chmod +x ./deploy/deploy.sh
- chmod 600 /tmp/deploy_rsa
- eval "$(ssh-agent -s)"
- ssh-add /tmp/deploy_rsa
install:
- pip install -r requirements.txt
services:
- redis-server
before_script:
- rq worker &
script: python run_tests.py
notifications:
  email: false
after_success:
- killall rq
- echo "Deploying."
- sh ./deploy/deploy.sh
